# -*- coding: utf-8 -*-
"""frauddetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AwCqvL1dDmE5xsWdRvs3QbSLlaeOySCC
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns

# Load your dataset
df = pd.read_csv('/content/creditcard.csv')  # Replace with your actual file path

print(df.head())
print(df.info())
print(df.tail())

print(df.isnull().sum())

import matplotlib.pyplot as plt
import seaborn as sns

# Distribution of target variable
plt.figure(figsize=(6, 4))
sns.countplot(x='Class', data=df)
plt.title('Distribution of Target Variable (Class)')
plt.show()

scaler = StandardScaler()
df_scaled = pd.DataFrame(scaler.fit_transform(df.drop(['Time', 'Amount', 'Class'], axis=1)), columns=df.columns[1:-2])

# Adding back the 'Time', 'Amount', and 'Class' columns
df_scaled['Time'] = df['Time']
df_scaled['Amount'] = df['Amount']
df_scaled['Class'] = df['Class']

# Correlation matrix
corr_matrix = df.corr()

# Plotting the correlation matrix
plt.figure(figsize=(20, 15))
sns.heatmap(corr_matrix, annot=True, fmt='.2f', cmap='virdis', linewidths=0.5)
plt.title('Correlation Matrix')
plt.show()

# Correlation with target variable
corr_with_target = corr_matrix['Class'].sort_values(ascending=False)
print(corr_with_target)

X = df_scaled.drop('Class', axis=1)
y = df_scaled['Class']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Check for NaN values in y_train
print("Missing values in y_train:", y_train.isnull().sum())

# Drop rows with missing target values
X_train = X_train[~y_train.isnull()]
y_train = y_train.dropna()

# Fill missing target values with the most frequent class
y_train = y_train.fillna(y_train.mode()[0])

from sklearn.tree import DecisionTreeClassifier

# Initialize the Decision Tree Classifier
dt_classifier = DecisionTreeClassifier(random_state=42)

# Fit the model to the training data
dt_classifier.fit(X_train, y_train)

# Predict the outcomes on the test set
y_pred = dt_classifier.predict(X_test)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt="d", cmap='Blues')
plt.title("Decision Tree Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# Classification Report
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Accuracy Score
print(f"Accuracy: {accuracy_score(y_test, y_pred)}")